language: python
sudo: false
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
cache: pip
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6e98b3e8e789_key -iv $encrypted_6e98b3e8e789_iv -in .env.enc -out .env -d || true'
install: pip install tox-travis
script: tox
before_deploy:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
- pip install --editable .
deploy:
  provider: script
  script: docs/publish.sh
  skip_cleanup: true
  on:
    python: '2.7'
    all_branches: true
